### ISSUE TITLE
Pling.com tar.xz archive fails to extract

### ISSUE THREAD

**Issue by TheRealOne78** [ItzSelenux/pixelitos-icon-theme#25]
Like the title of this issue says, tar fails to extract the contents of the 'pixelitos.tar.xz' file.

Using `tar -xfv ./pixelitos.tar.xz` fails with the following message:
```
$ tar -xfv ./pixelitos.tar.xz
...
pixelitos/16/apps/system-logout.png
pixelitos/16/apps/distributor-logo-zorin.png
pixelitos/16/mimetypes/application-x-lzip-compressed-tar.png
tar: Exiting with failure status due to previous errors
```

Using [Xarchiver](https://en.wikipedia.org/wiki/Xarchiver) fails as well, which uses the `/bin/gtar -x --no-recursion --no-wildcards -f '/tmp/xa-TW1481/xa-tmp.decompressed' -C /home/therealone/tmp --` command:
![image](https://github.com/ItzSelenux/pixelitos-icon-theme/assets/53640879/db55b2b0-a013-41e4-b120-31d952020129)

I can extract some icons, however there is a handful ammount that's missing.

**Comment by ItzSelenux** [comment]
fixed, now i used zip archiver and now there is not problems while extracting
