### ISSUE TITLE
Dosbox Icon Request

### ISSUE THREAD

**Issue by Lazorne** [ItzSelenux/pixelitos-icon-theme#41]
Program Name: Dosbox

https://flathub.org/apps/com.dosbox.DOSBox

https://flathub.org/_next/image?url=https%3A%2F%2Fdl.flathub.org%2Fmedia%2Fcom%2Fdosbox%2FDOSBox%2F9be056ed2b101b8e1621ffd5b73b94ef%2Ficons%2F128x128%2Fcom.dosbox.DOSBox.png&w=128&q=75

**Comment by ItzSelenux** [comment]
Is even possible to do that logo without messing it? this is my best attemp
![image](https://github.com/user-attachments/assets/9fe0dec4-dddc-4c42-bff3-e800803e76c0)
