### ISSUE TITLE
FinalBurn Neo Icon Request

### ISSUE THREAD

**Issue by Lazorne** [ItzSelenux/pixelitos-icon-theme#51]
Program Name: FBNeo

https://github.com/finalburnneo/FBNeo
https://emulation.gametechwiki.com/index.php/File:FBlogo.png

**Comment by ItzSelenux** [comment]
Using another (more popular) logo:
![image](https://github.com/user-attachments/assets/fa3876e4-bae3-4104-ba76-b3b47e71ed9b)
